version: 2

orbs:
  gh-release: escaletech/gh-conventional-release@0.1

jobs:
  build-and-test:
    docker:
      - image: circleci/node:12
      - image: circleci/redis:4-alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Build
          command: npm run build
      - run:
          name: Build docs
          command: npm run docs
      - persist_to_workspace:
          root: .
          paths:
            - docs
            - lib

  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish package
          command: npm publish

  docs-deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install and configure dependencies
          command: |
            npm install gh-pages@2.1.1
            git config user.email "ci-build@escale.com.br"
            git config user.name "ci-build"
            touch docs/.nojekyll
      - run:
          name: Deploy docs to gh-pages branch
          command: ./node_modules/.bin/gh-pages -t true --dist docs

release_only: &release_only
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v.*/

workflows:
  version: 2
  ci:
    jobs:
      - build-and-test:
          filters:
            branches: { ignore: gh-pages }
            tags: { ignore: /.*/ }
      - docs-deploy:
          filters:
            branches: { only: master }
            tags: { ignore: /.*/ }
          requires:
            - build-and-test
  release:
    jobs:
      - build-and-test:
          <<: *release_only
      - deploy:
          context: github-create-release
          <<: *release_only
          requires:
            - build-and-test
      - gh-release/create-release:
          context: github-create-release
          requires:
            - deploy
          <<: *release_only
